<?php
/**
 * Demo license plates & special equipment listings.
 * @return array<string, mixed>
 */
return [
    'brand_plates' => ['name' => 'License Plates', 'slug' => 'license-plates'],
    'plate_models' => ['Vanity', 'Standard', 'Collectible', 'Diplomatic', 'Commercial', 'Motorcycle'],
    'special_brands' => [
        ['Caterpillar', 'caterpillar'],
        ['JCB', 'jcb'],
        ['Komatsu', 'komatsu'],
        ['Volvo CE', 'volvo-ce'],
        ['Liebherr', 'liebherr'],
        ['MAN', 'man-trucks'],
        ['Bobcat', 'bobcat'],
        ['Hitachi', 'hitachi'],
    ],
    'plates' => [
        ['plate' => 'AA 7777 BB', 'slug' => 'plate-aa7777bb-vanity', 'model' => 'Vanity', 'price' => 18500, 'region' => 'Kyiv', 'city' => 'Kyiv', 'year' => 2024, 'featured' => 1,
         'desc' => [
             'uk' => 'ВІП-номер AA 7777 BB. Один власник, повний пакет документів для переоформлення в Україні.',
             'en' => 'VIP plate AA 7777 BB. One owner, full paperwork for transfer in Ukraine.',
             'ru' => 'VIP-номер AA 7777 BB. Один владелец, полный пакет документов для переоформления.',
             'no' => 'VIP-skilt AA 7777 BB. En eier, full dokumentasjon for omregistrering.',
         ]],
        ['plate' => 'KO 1234 AB', 'slug' => 'plate-ko1234ab', 'model' => 'Standard', 'price' => 850, 'region' => 'Odesa', 'city' => 'Odesa', 'year' => 2023, 'featured' => 0,
         'desc' => [
             'uk' => 'Стандартний номерний знак KO 1234 AB, регіон Одеса. Швидке оформлення.',
             'en' => 'Standard plate KO 1234 AB, Odesa region. Fast transfer.',
             'ru' => 'Стандартный номер KO 1234 AB, регион Одесса.',
             'no' => 'Standard skilt KO 1234 AB, Odesa-regionen.',
         ]],
        ['plate' => 'BC 007 OO', 'slug' => 'plate-bc007oo-collectible', 'model' => 'Collectible', 'price' => 4200, 'region' => 'Lviv', 'city' => 'Lviv', 'year' => 2022, 'featured' => 1,
         'desc' => [
             'uk' => 'Колекційний номер BC 007 OO — рідкісна комбінація цифр.',
             'en' => 'Collectible plate BC 007 OO — rare digit combination.',
             'ru' => 'Коллекционный номер BC 007 OO — редкая комбинация.',
             'no' => 'Samlerskilt BC 007 OO — sjelden tallkombinasjon.',
         ]],
        ['plate' => 'AI 8888 IT', 'slug' => 'plate-ai8888it-vanity', 'model' => 'Vanity', 'price' => 12000, 'region' => 'Dnipro', 'city' => 'Dnipro', 'year' => 2024, 'featured' => 0,
         'desc' => [
             'uk' => 'Престижний номер AI 8888 IT для бізнес-авто.',
             'en' => 'Prestige plate AI 8888 IT for business vehicles.',
             'ru' => 'Престижный номер AI 8888 IT для бизнес-авто.',
             'no' => 'Prestisjeskilt AI 8888 IT for firmabiler.',
         ]],
        ['plate' => 'CE 2024 NO', 'slug' => 'plate-ce2024no', 'model' => 'Standard', 'price' => 650, 'region' => 'Oslo', 'city' => 'Oslo', 'year' => 2024, 'featured' => 0,
         'desc' => [
             'uk' => 'Норвезький номер CE 2024 NO — готовий до передачі.',
             'en' => 'Norwegian plate CE 2024 NO — ready for transfer.',
             'ru' => 'Норвежский номер CE 2024 NO — готов к передаче.',
             'no' => 'Norsk skilt CE 2024 NO — klar for overdragelse.',
         ]],
        ['plate' => 'DP 001 CD', 'slug' => 'plate-dp001cd-diplomatic', 'model' => 'Diplomatic', 'price' => 2500, 'region' => 'Kyiv', 'city' => 'Kyiv', 'year' => 2021, 'featured' => 0,
         'desc' => [
             'uk' => 'Дипломатичний серію DP 001 CD — рідкісний тип знака.',
             'en' => 'Diplomatic series DP 001 CD — rare plate type.',
             'ru' => 'Дипломатическая серия DP 001 CD.',
             'no' => 'Diplomatisk serie DP 001 CD.',
         ]],
        ['plate' => 'EL 9999 EV', 'slug' => 'plate-el9999ev-vanity', 'model' => 'Vanity', 'price' => 9800, 'region' => 'Oslo', 'city' => 'Oslo', 'year' => 2025, 'featured' => 1,
         'desc' => [
             'uk' => 'Норвезький преміум-номер EL 9999 EV — ідеально для електромобіля.',
             'en' => 'Norwegian premium plate EL 9999 EV — perfect for an electric car.',
             'ru' => 'Норвежский премиум-номер EL 9999 EV — для электромобиля.',
             'no' => 'Norsk premiumskilt EL 9999 EV — perfekt for elbil.',
         ]],
        ['plate' => 'DR 2026 GM', 'slug' => 'plate-dr2026gm', 'model' => 'Standard', 'price' => 720, 'region' => 'Viken', 'city' => 'Drammen', 'year' => 2026, 'featured' => 0,
         'desc' => [
             'uk' => 'Номер Drammen DR 2026 GM — демо для автосалону Global Motors.',
             'en' => 'Drammen plate DR 2026 GM — demo listing for Global Motors dealership.',
             'ru' => 'Номер Drammen DR 2026 GM — демо для автосалона Global Motors.',
             'no' => 'Drammen-skilt DR 2026 GM — demo for Global Motors.',
         ]],
        ['plate' => 'AB 12345', 'slug' => 'plate-ab12345-bergen', 'model' => 'Standard', 'price' => 590, 'region' => 'Vestland', 'city' => 'Bergen', 'year' => 2023, 'featured' => 0,
         'desc' => [
             'uk' => 'Норвезький стандартний номер Bergen AB 12345.',
             'en' => 'Standard Norwegian plate Bergen AB 12345.',
             'ru' => 'Стандартный норвежский номер Bergen AB 12345.',
             'no' => 'Standard norsk skilt Bergen AB 12345.',
         ]],
        ['plate' => 'VIP 1 BH', 'slug' => 'plate-vip1bh-collectible', 'model' => 'Collectible', 'price' => 15500, 'region' => 'Kyiv', 'city' => 'Kyiv', 'year' => 2020, 'featured' => 1,
         'desc' => [
             'uk' => 'Колекційний короткий номер VIP 1 BH — статусний знак для преміум-авто.',
             'en' => 'Collectible short plate VIP 1 BH — status plate for premium cars.',
             'ru' => 'Коллекционный короткий номер VIP 1 BH.',
             'no' => 'Samlerskilt VIP 1 BH — statusskilt for premiumbiler.',
         ]],
        ['plate' => 'B-EV 2024', 'slug' => 'plate-b-ev2024-berlin', 'model' => 'Commercial', 'price' => 1100, 'region' => 'Berlin', 'city' => 'Berlin', 'year' => 2024, 'featured' => 0,
         'desc' => [
             'uk' => 'Комерційний європейський номер B-EV 2024 для електрофургона.',
             'en' => 'European commercial plate B-EV 2024 for electric van fleet.',
             'ru' => 'Коммерческий европейский номер B-EV 2024 для электрофургона.',
             'no' => 'Europeisk næringsskilt B-EV 2024 for el-varebil.',
         ]],
        ['plate' => 'WA 5555 ZZ', 'slug' => 'plate-wa5555zz-warsaw', 'model' => 'Vanity', 'price' => 3200, 'region' => 'Mazowieckie', 'city' => 'Warsaw', 'year' => 2022, 'featured' => 0,
         'desc' => [
             'uk' => 'Польський vanity-номер WA 5555 ZZ — п’ятірки, легко запам’ятати.',
             'en' => 'Polish vanity plate WA 5555 ZZ — repeating fives, easy to remember.',
             'ru' => 'Польский vanity-номер WA 5555 ZZ.',
             'no' => 'Polsk vanity-skilt WA 5555 ZZ.',
         ]],
        ['plate' => 'MC 77 RR', 'slug' => 'plate-mc77rr-motorcycle', 'model' => 'Motorcycle', 'price' => 1800, 'region' => 'Lviv', 'city' => 'Lviv', 'year' => 2023, 'featured' => 0,
         'desc' => [
             'uk' => 'Мотоциклетний номер MC 77 RR — для спортбайка або кастома.',
             'en' => 'Motorcycle plate MC 77 RR — for sport bike or custom build.',
             'ru' => 'Мотоциклетный номер MC 77 RR.',
             'no' => 'Motorsykkelskilt MC 77 RR.',
         ]],
        ['plate' => 'TR 4040 XX', 'slug' => 'plate-tr4040xx-commercial', 'model' => 'Commercial', 'price' => 2100, 'region' => 'Kharkiv', 'city' => 'Kharkiv', 'year' => 2021, 'featured' => 0,
         'desc' => [
             'uk' => 'Комерційний номер TR 4040 XX для вантажівки або автопарку.',
             'en' => 'Commercial plate TR 4040 XX for truck or fleet vehicle.',
             'ru' => 'Коммерческий номер TR 4040 XX для грузовика.',
             'no' => 'Næringsskilt TR 4040 XX for lastebil.',
         ]],
    ],
    'special' => [
        ['brand' => 'Caterpillar', 'model' => '320 GC', 'slug' => 'caterpillar-320gc-2018', 'year' => 2018, 'price' => 89000, 'hours' => 4200, 'body' => 'excavator', 'region' => 'Kyiv', 'city' => 'Kyiv', 'featured' => 1,
         'img' => 'https://images.unsplash.com/photo-1581094271901-ef2dfa9f7ab1?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Екскаватор Caterpillar 320 GC 2018, 4200 м/год, гідравліка в ідеалі, готовий до роботи.',
             'en' => 'Caterpillar 320 GC excavator 2018, 4200 hours, hydraulics in excellent condition.',
             'ru' => 'Экскаватор Caterpillar 320 GC 2018, 4200 м/ч, гидравлика в отличном состоянии.',
             'no' => 'Caterpillar 320 GC gravemaskin 2018, 4200 timer, hydraulikk i topp stand.',
         ]],
        ['brand' => 'JCB', 'model' => '3CX', 'slug' => 'jcb-3cx-2019', 'year' => 2019, 'price' => 52000, 'hours' => 3100, 'body' => 'backhoe', 'region' => 'Lviv', 'city' => 'Lviv', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'JCB 3CX backhoe loader 2019 — універсальна спецтехніка для будівництва.',
             'en' => 'JCB 3CX backhoe loader 2019 — versatile construction equipment.',
             'ru' => 'JCB 3CX погрузчик-экскаватор 2019 — универсальная спецтехника.',
             'no' => 'JCB 3CX gravemaskin 2019 — allsidig anleggsmaskin.',
         ]],
        ['brand' => 'Komatsu', 'model' => 'PC210', 'slug' => 'komatsu-pc210-2017', 'year' => 2017, 'price' => 78000, 'hours' => 5800, 'body' => 'excavator', 'region' => 'Odesa', 'city' => 'Odesa', 'featured' => 1,
         'img' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Komatsu PC210 гусеничний екскаватор, 5800 м/год, ковш 1.0 м³.',
             'en' => 'Komatsu PC210 crawler excavator, 5800 hours, 1.0 m³ bucket.',
             'ru' => 'Komatsu PC210 гусеничный экскаватор, 5800 м/ч.',
             'no' => 'Komatsu PC210 beltegraver, 5800 timer.',
         ]],
        ['brand' => 'Volvo CE', 'model' => 'L90H', 'slug' => 'volvo-l90h-2020', 'year' => 2020, 'price' => 95000, 'hours' => 2900, 'body' => 'loader', 'region' => 'Oslo', 'city' => 'Oslo', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Volvo L90H колесний навантажувач 2020, низький пробіг по мотогодинах.',
             'en' => 'Volvo L90H wheel loader 2020, low operating hours.',
             'ru' => 'Volvo L90H колесный погрузчик 2020, малый наработка.',
             'no' => 'Volvo L90H hjullaster 2020, lave timer.',
         ]],
        ['brand' => 'Liebherr', 'model' => 'LTM 1050', 'slug' => 'liebherr-ltm1050-2015', 'year' => 2015, 'price' => 210000, 'hours' => 8900, 'body' => 'crane', 'region' => 'Dnipro', 'city' => 'Dnipro', 'featured' => 1,
         'img' => 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Liebherr LTM 1050 автокран 2015, 50 т, повний пакет ТО.',
             'en' => 'Liebherr LTM 1050 mobile crane 2015, 50 t capacity.',
             'ru' => 'Liebherr LTM 1050 автокран 2015, 50 т.',
             'no' => 'Liebherr LTM 1050 mobilkran 2015, 50 t kapasitet.',
         ]],
        ['brand' => 'MAN', 'model' => 'TGS 41.480', 'slug' => 'man-tgs-2016', 'year' => 2016, 'price' => 68000, 'hours' => 410000, 'body' => 'truck_heavy', 'region' => 'Kharkiv', 'city' => 'Kharkiv', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'MAN TGS 41.480 важкий вантажівка 2016, 8x4, для будівництва та логістики.',
             'en' => 'MAN TGS 41.480 heavy truck 2016, 8x4 chassis for construction logistics.',
             'ru' => 'MAN TGS 41.480 тяжёлый грузовик 2016, 8x4.',
             'no' => 'MAN TGS 41.480 tung lastebil 2016, 8x4.',
         ]],
        ['brand' => 'Caterpillar', 'model' => 'D6T', 'slug' => 'caterpillar-d6t-2014', 'year' => 2014, 'price' => 115000, 'hours' => 7200, 'body' => 'bulldozer', 'region' => 'Viken', 'city' => 'Drammen', 'featured' => 1,
         'img' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Бульдозер Caterpillar D6T 2014 — земляні роботи, кар’єри, дорожнє будівництво в Норвегії.',
             'en' => 'Caterpillar D6T bulldozer 2014 — earthworks and road construction in Norway.',
             'ru' => 'Бульдозер Caterpillar D6T 2014 — земляные работы в Норвегии.',
             'no' => 'Caterpillar D6T bulldoser 2014 — grunnarbeid og veibygg i Norge.',
         ]],
        ['brand' => 'Bobcat', 'model' => 'T770', 'slug' => 'bobcat-t770-2021', 'year' => 2021, 'price' => 42000, 'hours' => 1800, 'body' => 'loader', 'region' => 'Vestland', 'city' => 'Bergen', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Bobcat T770 компактний навантажувач 2021 — мінімальні мотогодини, ідеальний для складів.',
             'en' => 'Bobcat T770 compact loader 2021 — low hours, ideal for warehouses.',
             'ru' => 'Bobcat T770 компактный погрузчик 2021 — малый наработка.',
             'no' => 'Bobcat T770 kompaktlastare 2021 — lave timer, ideell for lager.',
         ]],
        ['brand' => 'Hitachi', 'model' => 'ZX350', 'slug' => 'hitachi-zx350-2016', 'year' => 2016, 'price' => 102000, 'hours' => 6400, 'body' => 'excavator', 'region' => 'Berlin', 'city' => 'Berlin', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1590642917089-cfecab765d38?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Hitachi ZX350 гусеничний екскаватор 2016 — 35 т, Європа, сервісна книжка.',
             'en' => 'Hitachi ZX350 crawler excavator 2016 — 35 t, Europe, full service history.',
             'ru' => 'Hitachi ZX350 гусеничный экскаватор 2016 — 35 т, Европа.',
             'no' => 'Hitachi ZX350 beltegraver 2016 — 35 t, Europa, full servicehistorikk.',
         ]],
        ['brand' => 'JCB', 'model' => 'Fastrac 4220', 'slug' => 'jcb-fastrac-4220-2018', 'year' => 2018, 'price' => 58000, 'hours' => 3900, 'body' => 'tractor', 'region' => 'Mazowieckie', 'city' => 'Warsaw', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'JCB Fastrac 4220 трактор 2018 — швидкий сільськогосподарський тягач для фермерських господарств.',
             'en' => 'JCB Fastrac 4220 tractor 2018 — high-speed agricultural tractor.',
             'ru' => 'JCB Fastrac 4220 трактор 2018 — сельхоз тягач.',
             'no' => 'JCB Fastrac 4220 traktor 2018 — høyhastighets landbrukstraktor.',
         ]],
        ['brand' => 'Volvo CE', 'model' => 'EC220E', 'slug' => 'volvo-ec220e-2019', 'year' => 2019, 'price' => 118000, 'hours' => 4500, 'body' => 'excavator', 'region' => 'Rogaland', 'city' => 'Stavanger', 'featured' => 1,
         'img' => 'https://images.unsplash.com/photo-1581092921461-39bdaa4d4c82?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Volvo EC220E екскаватор 2019 — нафтово-газові проєкти Stavanger, низькі мотогодини.',
             'en' => 'Volvo EC220E excavator 2019 — Stavanger oil & gas projects, low hours.',
             'ru' => 'Volvo EC220E экскаватор 2019 — проекты Stavanger, малый наработка.',
             'no' => 'Volvo EC220E gravemaskin 2019 — Stavanger olje & gass, lave timer.',
         ]],
        ['brand' => 'Komatsu', 'model' => 'WA380', 'slug' => 'komatsu-wa380-2018', 'year' => 2018, 'price' => 87000, 'hours' => 5100, 'body' => 'loader', 'region' => 'Trøndelag', 'city' => 'Trondheim', 'featured' => 0,
         'img' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&h=600&q=80',
         'desc' => [
             'uk' => 'Komatsu WA380 колесний навантажувач 2018 — сніг, порти, лісозаготівля в Норвегії.',
             'en' => 'Komatsu WA380 wheel loader 2018 — snow, ports, forestry work in Norway.',
             'ru' => 'Komatsu WA380 колесный погрузчик 2018 — снег, порты, лес в Норвегии.',
             'no' => 'Komatsu WA380 hjullaster 2018 — snø, havner, skogbruk i Norge.',
         ]],
    ],
];